/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_CSE4116_Final */

#ifndef _Included_org_example_ndk_CSE4116_Final
#define _Included_org_example_ndk_CSE4116_Final
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    openSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_openSwitch
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    closeSwitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_closeSwitch
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    readSwitch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_readSwitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    openDot
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_openDot
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    openFND
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_openFND
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    openLCD
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_openLCD
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    closeLCD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_closeLCD
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    closeFND
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_closeFND
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    closeDOT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_closeDOT
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    writeLCDFirstLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_writeLCDFirstLine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    writeLCDSecondLine
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_writeLCDSecondLine
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    closeDot
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_CSE4116_1Final_closeDot
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_example_ndk_CSE4116_Final
 * Method:    startPushSwitch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_startPushSwitch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
