/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_CSE4116_Final_FpgaPushSwitch */

#ifndef _Included_org_example_ndk_CSE4116_Final_FpgaPushSwitch
#define _Included_org_example_ndk_CSE4116_Final_FpgaPushSwitch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_CSE4116_Final_FpgaPushSwitch
 * Method:    startPushSwitch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_CSE4116_1Final_00024FpgaPushSwitch_startPushSwitch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
